import path, { resolve } from "path";
import { defineConfig, loadEnv } from "vite";
import minimist from "minimist";
import { viteStaticCopy } from "vite-plugin-static-copy";
import livereload from "rollup-plugin-livereload";
import { svelte } from "@sveltejs/vite-plugin-svelte";
import zipPack from "vite-plugin-zip-pack";
import fg from "fast-glob";
import fs from "fs";
import esbuild from "esbuild";

function loadTsFile(filePath: string) {
  const result = esbuild.buildSync({
    entryPoints: [filePath],
    bundle: true,
    write: false,
    format: "cjs",
    platform: "node",
  });
  const code = result.outputFiles[0].text;
  const m = { exports: {} as any };
  const fn = new Function("module", "exports", "require", "__dirname", "__filename", code);
  fn(m, m.exports, require, path.dirname(filePath), filePath);
  return m.exports;
}

function writeIfChanged(filePath: string, content: string) {
  if (fs.existsSync(filePath)) {
    const existing = fs.readFileSync(filePath, "utf-8");
    if (existing === content) {
      return;
    }
  }
  fs.writeFileSync(filePath, content, "utf-8");
}

async function generateTranslations() {
  const partsDir = resolve(__dirname, "src/translations/parts");
  if (!fs.existsSync(partsDir)) {
    fs.mkdirSync(partsDir, { recursive: true });
  }

  const files = await fg("src/translations/parts/*.ts");
  
  const enImports = files.map((f, i) => `import { en as part${i} } from "./parts/${path.basename(f, ".ts")}";`).join("\n");
  const enSpreads = files.map((_, i) => `  ...part${i},`).join("\n");
  const enCode = `// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT DIRECTLY.
${enImports}

export const en = {
  menuByURL: "Send by URL",
  menuByScript: "Send by Script",
  cancel: "Cancel",
  save: "Save",
  linkToWiki: "Link to Reference",
  wikiToLink: "Reference to Link",
  hrefToText: "Reference/Link to Text",
  hrefToTextIncludeA: "Reference/Link (incl. <a>) to Text",
  strongToText: "Bold to Text",
  markToText: "Highlight to Text",
  tagToText: "Tag to Text",
  cleanRefSelf: "Clean Self Reference",
  convertMenu: "Adjust Inline Elements",
  formatContent: "Format Content",

${enSpreads}
};
`;
  writeIfChanged(resolve(__dirname, "src/translations/en.ts"), enCode);

  const zhImports = files.map((f, i) => `import { zhCN as part${i} } from "./parts/${path.basename(f, ".ts")}";`).join("\n");
  const zhSpreads = files.map((_, i) => `  ...part${i},`).join("\n");
  const zhCode = `// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT DIRECTLY.
import { en } from "./en";
${zhImports}

export const zhCN: typeof en = {
  menuByURL: "通过URL发送到",
  menuByScript: "通过Script发送到",
  cancel: "取消",
  save: "保存",
  linkToWiki: "块超链接👉引用",
  wikiToLink: "引用👉块超链接",
  hrefToText: "引用/块超链接👉文本",
  hrefToTextIncludeA: "引用/链接👉文本",
  strongToText: "粗体👉文本",
  markToText: "标注👉文本",
  tagToText: "标签👉文本",
  cleanRefSelf: "清理文档自身的引用",
  convertMenu: "调整行内元素",
  formatContent: "格式化文本",

${zhSpreads}
};
`;
  writeIfChanged(resolve(__dirname, "src/translations/zh-CN.ts"), zhCode);
  console.log("--> [i18n] Autogenerated en.ts and zh-CN.ts files (if changed).");
}

const args = minimist(process.argv.slice(2));
const isWatch = args.watch || args.w || false;
// const devDistDir = "./dev"
const devDistDir = "/Users/hqweay/SiYuan/data/plugins/siyuan-hqweay-go";
const distDir = isWatch ? devDistDir : "./dist";

console.log("isWatch=>", isWatch);
console.log("distDir=>", distDir);

export default defineConfig({
  resolve: {
    alias: {
      "@": resolve(__dirname, "src"),
    },
  },

  plugins: [
    svelte(),
    {
      name: "i18n-generate",
      async buildStart() {
        // 1. 扫描 parts 自动构建主入口 TS 文件
        await generateTranslations();

        // 2. 利用 esbuild 在内存中秒级编译并运行 TS，规避 Node.js 对 .ts 扩展名的加载限制
        const { en } = loadTsFile(resolve(__dirname, "src/translations/en.ts"));
        const { zhCN } = loadTsFile(resolve(__dirname, "src/translations/zh-CN.ts"));

        const i18nDir = resolve(__dirname, "public/i18n");
        if (!fs.existsSync(i18nDir)) {
          fs.mkdirSync(i18nDir, { recursive: true });
        }
        writeIfChanged(
          resolve(i18nDir, "zh-CN.json"),
          JSON.stringify(zhCN, null, 2)
        );
        writeIfChanged(
          resolve(i18nDir, "en.json"),
          JSON.stringify(en, null, 2)
        );
        console.log("--> [i18n] Generated JSON files from TS definitions (if changed).");
      },
    },

    viteStaticCopy({
      targets: [
        {
          src: "./README*.md",
          dest: "./",
        },
        {
          src: "./plugin.json",
          dest: "./",
        },
        {
          src: "./preview.png",
          dest: "./",
        },
        {
          src: "./icon.png",
          dest: "./",
        },
      ],
    }),
  ],

  // https://github.com/vitejs/vite/issues/1930
  // https://vitejs.dev/guide/env-and-mode.html#env-files
  // https://github.com/vitejs/vite/discussions/3058#discussioncomment-2115319
  // 在这里自定义变量
  define: {
    "process.env.DEV_MODE": `"${isWatch}"`,
    "process.env.NODE_ENV": JSON.stringify(process.env.NODE_ENV),
  },

  build: {
    // 输出路径
    outDir: distDir,
    emptyOutDir: false,

    // 构建后是否生成 source map 文件
    sourcemap: false,

    // 设置为 false 可以禁用最小化混淆
    // 或是用来指定是应用哪种混淆器
    // boolean | 'terser' | 'esbuild'
    // 不压缩，用于调试
    minify: !isWatch,

    lib: {
      // Could also be a dictionary or array of multiple entry points
      entry: resolve(__dirname, "src/index.ts"),
      // the proper extensions will be added
      fileName: "index",
      formats: ["cjs"],
    },
    rollupOptions: {
      plugins: [
        ...(isWatch
          ? [
              livereload({
                watch: devDistDir,
                clientUrl: "http://localhost:35729/livereload.js?snipver=1",
              }),
              {
                //监听静态资源文件
                name: "watch-external",
                async buildStart() {
                  const files = await fg([
                    "public/i18n/**",
                    "src/translations/**",
                    "./README*.md",
                    "./plugin.json",
                  ]);
                  for (let file of files) {
                    this.addWatchFile(file);
                  }
                },
              },
            ]
          : [
              zipPack({
                inDir: "./dist",
                outDir: "./",
                outFileName: "package.zip",
              }),
            ]),
      ],

      // make sure to externalize deps that shouldn't be bundled
      // into your library
      external: ["siyuan", "process"],

      output: {
        entryFileNames: "[name].js",
        assetFileNames: (assetInfo) => {
          if (assetInfo.name === "style.css") {
            return "index.css";
          }
          return assetInfo.name;
        },
      },
    },
  },
});
