export default {
  name: "ocr",
  displayName: "lets-ocr.displayName",
  description: "lets-ocr.description",
  version: "1.0.0",
  author: "hqweay",
  settings: [
    {
      type: "select",
      title: "lets-ocr.ocrMethod",
      description: "lets-ocr.ocrMethodDesc",
      key: "ocrMethod",
      value: "macOSVision",
      options: {
        macOSVision: "使用 MacOS Vision OCR",
        umi: "使用 umi OCR",
        tesseract: "使用 tesseract OCR",
      },
    },
    {
      type: "textarea",
      title: "lets-ocr.umiOCRServer",
      description: "lets-ocr.umiOCRServerDesc",
      key: "umiOCRServer",
      value: "",
      placeholder: "",
    },
    {
      type: "checkbox",
      title: "lets-ocr.autoRemoveLineBreaks",
      description: "lets-ocr.autoRemoveLineBreaksDesc",
      key: "autoRemoveLineBreaks",
      value: false,
    },
    {
      type: "checkbox",
      title: "lets-ocr.removeLineBreaks",
      description: "lets-ocr.removeLineBreaksDesc",
      key: "removeLineBreaks",
      value: false,
    },
    {
      type: "checkbox",
      title: "lets-ocr.removeBlankInChinese",
      description: "lets-ocr.removeBlankInChineseDesc",
      key: "removeBlankInChinese",
      value: false,
    },
    {
      type: "checkbox",
      title: "lets-ocr.formatWithPangu",
      description: "lets-ocr.formatWithPanguDesc",
      key: "formatWithPangu",
      value: false,
    },
  ],
};
