export default {
  name: "ocr",
  displayName: "OCR 图片识别",
  description: "Mac 支持使用本地 OCR 功能，提供 OCR 文本的预处理等",
  version: "1.0.0",
  author: "hqweay",
  settings: [
    {
      type: "select",
      title: "方案",
      description: "方案",
      key: "ocrMethod",
      value: "macOSVision",
      options: {
        macOSVision: "使用 MacOS Vision OCR",
        umi: "使用 umi OCR",
        tesseract: "使用 tesseract OCR",
      },
    },
    {
      type: "textarea",
      title: "umi-ocr 服务地址",
      description: "umi-ocr 服务地址",
      key: "umiOCRServer",
      value: "",
      placeholder: "",
    },
    {
      type: "checkbox",
      title: "自动移除换行",
      description: "通过每行结尾是否存在标点自动判断移除换行",
      key: "autoRemoveLineBreaks",
      value: false,
    },
    {
      type: "checkbox",
      title: "移除换行符",
      description: "OCR 识别后是否移除文本中的换行符",
      key: "removeLineBreaks",
      value: false,
    },
    {
      type: "checkbox",
      title: "移除中文内的空格",
      description: "移除中文内的空格",
      key: "removeBlankInChinese",
      value: false,
    },
    {
      type: "checkbox",
      title: "调用 pangu 格式化",
      description: "调用 pangu 格式化",
      key: "formatWithPangu",
      value: false,
    },
  ],
};
