import { PluginMetadata } from "@/types/plugin";

const pluginMetadata: PluginMetadata = {
  name: "nav-helper",
  displayName: "【实验】导航助手",
  description:
    "支持 PC、移动端。快捷前进、后退、今日日记、父文档、保存至数据库……",
  version: "1.0.0",
  author: "hqweay",
  settings: [
    {
      type: "select",
      title: "启用底部导航栏",
      description: "移动端、PC 端",
      key: "enableBottomNav",
      value: "both",
      options: {
        mobile: "移动端",
        pc: "PC 端",
        both: "移动端、PC 端",
      },
    },
    {
      type: "checkbox",
      title: "仅在主界面显示导航",
      description: "导航栏只在主文档界面显示（进入设置页等隐藏）",
      key: "navJustInMain",
      value: true,
    },
    {
      type: "checkbox",
      title: "点击后隐藏子菜单",
      description: "比方说点击「导航」里的「跳转到父文档」后是否隐藏子菜单",
      key: "hideSubmenu",
      value: false,
    },
    {
      type: "select",
      title: "显示返回按钮",
      description: "在导航栏中显示返回按钮",
      key: "showBackButton",
      value: "both",
      options: {
        mobile: "移动端",
        pc: "PC 端",
        both: "移动端、PC 端",
        none: "不显示",
      },
    },
    {
      type: "textinput",
      title: "笔记本ID",
      description: "指定导航的默认笔记本ID（可选）",
      key: "noteBookID",
      value: "20240330144726-gs2xey6",
      placeholder: "",
    },
    {
      type: "select",
      title: "显示前进按钮",
      description: "在导航栏中显示前进按钮",
      key: "showForwardButton",
      value: "both",
      options: {
        mobile: "移动端",
        pc: "PC 端",
        both: "移动端、PC 端",
        none: "不显示",
      },
    },
    {
      type: "select",
      title: "显示仪表盘按钮",
      description: "在导航栏中显示仪表盘按钮",
      key: "showDashBoard",
      value: "both",
      options: {
        mobile: "移动端",
        pc: "PC 端",
        both: "移动端、PC 端",
        none: "不显示",
      },
    },
    {
      type: "textarea",
      title: "仪表盘按钮配置",
      description:
        "支持 siyuan://plugins/siyuan-hqweay-go/flow 或 siyuan://plugins/siyuan-hqweay-go/open",
      key: "dashBoardLink",
      value: "siyuan://plugins/siyuan-hqweay-go/open",
      placeholder: "siyuan://plugins/siyuan-hqweay-go/open",
      height: "100px",
    },
    {
      type: "select",
      title: "显示随机按钮",
      description: "在导航栏中显示随机文档按钮",
      key: "showRandomButton",
      value: "both",
      options: {
        mobile: "移动端",
        pc: "PC 端",
        both: "移动端、PC 端",
        none: "不显示",
      },
    },
    {
      type: "select",
      title: "显示自定义链接按钮",
      description: "在导航栏中显示自定义链接按钮",
      key: "showCustomLinksButton",
      value: "both",
      options: {
        mobile: "移动端",
        pc: "PC 端",
        both: "移动端、PC 端",
        none: "不显示",
      },
    },
    {
      type: "select",
      title: "显示今日笔记按钮",
      description: "在导航栏中显示今日笔记按钮",
      key: "showDailyNoteButton",
      value: "both",
      options: {
        mobile: "移动端",
        pc: "PC 端",
        both: "移动端、PC 端",
        none: "不显示",
      },
    },
    {
      type: "select",
      title: "显示导航菜单按钮",
      description: "在导航栏中显示导航菜单按钮",
      key: "showNavigationMenuButton",
      value: "both",
      options: {
        mobile: "移动端",
        pc: "PC 端",
        both: "移动端、PC 端",
        none: "不显示",
      },
    },
    {
      type: "select",
      title: "显示上下文按钮",
      description: "在导航栏中显示上下文导航按钮",
      key: "showContextButton",
      value: "both",
      options: {
        mobile: "移动端",
        pc: "PC 端",
        both: "移动端、PC 端",
        none: "不显示",
      },
    },
    {
      type: "textinput",
      title: "导航栏高度",
      description: "设置底部导航栏的高度",
      key: "navBarHeight",
      value: "60px",
      placeholder: "60px",
    },
    {
      type: "textinput",
      title: "背景颜色",
      description: "导航栏背景颜色",
      key: "backgroundColor",
      value: "#ffffff",
      placeholder: "#ffffff",
    },
    {
      type: "textinput",
      title: "按钮颜色",
      description: "导航栏按钮默认颜色",
      key: "buttonColor",
      value: "#333333",
      placeholder: "#333333",
    },
    {
      type: "textinput",
      title: "激活按钮颜色",
      description: "导航栏激活按钮颜色",
      key: "activeButtonColor",
      value: "#007aff",
      placeholder: "#007aff",
    },
    // {
    //   type: "textarea",
    //   title: "随机SQL",
    //   description: "用于随机选择文档的SQL语句",
    //   key: "randomSql",
    //   value: "SELECT id FROM blocks WHERE type = 'd'",
    //   placeholder: "SELECT id FROM blocks WHERE type = 'd'",
    // },
    {
      type: "textarea",
      title: "自定义链接",
      description: "自定义链接配置，每行一个，格式：标题====链接",
      key: "customLinks",
      value: `养恐龙====https://leay.net/====🐊
日记随机====select * from blocks where path like '%/20250126213235-a3tnoqb/%' and type='d'
草稿随机====select * from blocks where path like '%/20240406015842-137jie3/%' and type='d'
添加到写作数据库====20250914152140-n10qdtt====💾`,
      placeholder: "标题1====链接1\n标题2====链接2",
    },
  ],
};

export default pluginMetadata;
